# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default='pictures/None/no-img.jpg', upload_to='pictures/'),
        ),
    ]
